version: '3.2'
services:
  mysql:
    image: mysql:5.7.34
    hostname: mysql
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sub
volumes:
  db-data:
